### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?)

### ISSUE THREAD

**Issue by Ruff9** [thoughtbot/capybara_discoball#13]
I'm following [this article](https://robots.thoughtbot.com/faking-apis-in-development-and-staging), but I can't make capybara discoball work. I get this error:

```
Failure/Error: HTTParty.get(self.class.base_url + "/API/V1/programms", format: :json)

URI::InvalidURIError:
  bad URI(is not URI?): 127.0.0.1:49552/API/V1/programs
```

**Comment by jferris** [comment]
Does `self.class.base_url` include a protocol, like `http://`? If not, you'll need to prepend to the URL string. This might be a mistake in the article.

**Comment by Ruff9** [comment]
You're right, my bad. And you're also right, the article on Thoughbot'blog should be corrected.
